name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@69e8723ead994e9646a4f81be4c040e51209e354
    secrets: inherit
