name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@e748f0e8638655cb24f5239eb4c336b5e48dfb81
    secrets: inherit
